FROM node:22-alpine AS build
WORKDIR /app
COPY package.json package-lock.json* pnpm-lock.yaml* ./
COPY tsconfig.json tsconfig.base.json ./
COPY frontend ./frontend
COPY packages ./packages
RUN npm install
RUN npm run build --workspace superteacher-frontend

FROM node:22-alpine AS runtime
WORKDIR /app
COPY --from=build /app/frontend/dist /usr/share/nginx/html
RUN npm i -g serve
EXPOSE 4173
CMD ["serve", "-s", "/usr/share/nginx/html", "-l", "4173"]
